# Generated by Django 5.0.6 on 2024-05-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0002_channel_campaign_budgetallocation"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="budget_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
