# Generated by Django 5.0.6 on 2024-05-15 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_remove_budgetallocation_budget_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="budgetallocation",
            name="budget_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
