# Generated by Django 5.0.6 on 2024-05-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0005_budgetallocation_budget_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="budget_forecast",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
    ]
